name: Reid Sata
url: http://example.org
description: Some writing among other things.

permalink: /posts/:title/
paginate: 10
highlighter: true

sass:
  sass_dir: styles/_sass
  style: :compressed

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']