name: Reid Sata
url: http://rsata.com

permalink: :categories/posts/:title/
#paginate: 10
highlighter: pygments

sass:
  sass_dir: styles/_sass
  style: :compressed

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']