name: Reid Sata
url: http://example.org
description: Some writing amongst other things.

permalink: :categories/posts/:title/
paginate: 10
highlighter: pygments

sass:
  sass_dir: styles/_sass
  style: :compressed

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']