# Jekyll Resume Theme

# Site settings
title: Reid Sata Resume
email: reid.t.sata@gmail.com
description: Reid Sata's Resume
baseurl: ""
url: "http://rsata.com"
name: Reid Sata
job: recent grad
location: Portland, OR
languages: JavaScript, React, Node, SASS, etc.
github_username:  rsata
email_address: reid.t.sata@gmail.com
linkedin: rsata
instagram: reid_turtle

# Build settings
markdown: kramdown

navigation:
  - text: '> Experience'
    url: '#experience'
  - text: '> Coding'
    url: '#coding'
  - text: '> Activities &amp; Accomplishments'
    url: '#activities'
  - text: '> Education'
    url: '#education'